# Choisissez une image de base qui convient à votre application Node.js
FROM node:14-alpine

# Définir le répertoire de travail dans l'image Docker
WORKDIR /backend

# Copier le fichier package.json et installer les dépendances
COPY package.json .
RUN npm install

# Copier le reste des fichiers de l'application dans l'image Docker
COPY backend/ .

# Exposer le port que l'application va utiliser
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]