# Choisissez une image de base qui convient à votre application Node.js
FROM node:14-alpine

# Définir le répertoire de travail dans l'image Docker
WORKDIR /backend

# Copier les fichiers de l'application dans l'image Docker
COPY package.json package-lock.json ./backend/
COPY backend/server.js ./backend/

# Installer les dépendances de l'application
RUN npm install

# Exposer le port que l'application va utiliser
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]